# Specific settings for the COVER marker.

# Configuration of the images to be used.
[images]
# Images to get/use. This should basically be a list of existing image profile names as
# configured in imageprofile.ini.
images = ["s2-ndvi-weekly", {"s1-grd-sigma0-asc-weekly": ["VV", "VH"]}, {"s1-grd-sigma0-desc-weekly": ["VV", "VH"]}]

# Marker-specific configuration.
[marker]
markertype = ONBEDEKT

parceldata_aggregations_to_use = count, mean, median, stdev

[calc_marker_params]
# Minimum NDVI threshold, everything below this is considered "bare soil"
ndvi_threshold = 0.35

# Threshold for S1 ML probabilty to consider something as ONBEDEKT
ml_onbedekt_threshold = 0.65